from reportlab.lib.pagesizes import LETTER
from reportlab.lib.units import inch

PAGE_SIZE = LETTER
MARGIN_TOP = 0.5 * inch
MARGIN_BOTTOM = 0.5 * inch
MARGIN_SIDE = 0.6 * inch

FONT_NAME = "Times-Roman"
FONT_NAME_BOLD = "Times-Bold"
FONT_NAME_ITALIC = "Times-Italic"

NAME_SIZE = 22
TAGLINE_SIZE = 9.5
SECTION_SIZE = 10.5
ENTRY_TITLE_SIZE = 10
BODY_SIZE = 9.5
FONT_SIZE_LADDER = [9.5, 9.0, 8.5, 8.0]

LINE_LEADING = 12.5
RULE_COLOR = "#000000"
TEXT_COLOR = "#000000"

PHOTO_DIAMETER = 0.85 * inch
PHOTO_PATH = "~/resume_photo.jpg"

BULLET_INDENT = 14
SECTION_RULE_THICKNESS = 0.6
SECTION_GAP_AFTER = 4
ENTRY_GAP_AFTER = 2
HEADER_SECTION_GAP = 8
TAGLINE_LINE_COUNT = 1
SKILLS_LINE_GAP = 2
ACHIEVEMENTS_HEADER = "ACHIEVEMENTS"

HEADER_HEIGHT_FIXED = (
    (NAME_SIZE * 1.3)
    + (TAGLINE_SIZE * 1.3 * TAGLINE_LINE_COUNT)
    + HEADER_SECTION_GAP
)

SECTION_HEADER_HEIGHT = (SECTION_SIZE * 1.3) + SECTION_GAP_AFTER + SECTION_RULE_THICKNESS

ENTRY_ROW_HEIGHT = ENTRY_TITLE_SIZE * 1.4 + ENTRY_GAP_AFTER

EDUCATION_SECTION_NAME = "EDUCATION"
EXPERIENCE_SECTION_NAME = "EXPERIENCE"
PROJECTS_SECTION_NAME = "PROJECTS"
SKILLS_SECTION_NAME = "SKILLS"
